#!/bin/bash

:<<'hopper-stack-notice'

Copyright 2016 Hopper-Stack

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

hopper-stack-notice

# +------------------------------------------+
# | VARIABLES                                |
# +------------------------------------------+
if [ ! -f patch-server-rhel-profile ]; then
   echo
   echo " +-------------------------------------------------------------+"
   echo " |  No patch-server-rhel-profile file found in this directory  |"
   echo " +-------------------------------------------------------------+"
   echo
   exit
else
   source patch-server-rhel-profile
fi

# HTTP files
mkdir -p /var/www/html/$HTTPFILES
mkdir -p /var/www/html/$HTTPFILES/swift
mkdir -p /var/www/html/$HTTPFILES/glance
mkdir -p /var/www/html/$HTTPFILES/nagios
mkdir -p /var/www/html/$HTTPFILES/keepass
mkdir -p /var/www/html/$HTTPFILES/logstash
mkdir -p /var/www/html/$HTTPFILES/s3cmd
mkdir -p /var/www/html/$HTTPFILES/kickstart
PROXYDIR=/var/www/html/$HTTPFILES

mkdir /repos/$HTTPFILES
cp -r /var/www/html/$HTTPFILES /repos/$HTTPFILES

yum install -y mkisofs
mkisofs -r -o /iso/yumrepo.iso /repos


