#!/bin/bash

:<<'hopper-stack-notice'

Copyright 2016 Hopper~Stack

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

hopper-stack-notice

# +------------------------------------------+
# | VARIABLES                                |
# +------------------------------------------+
if [ ! -f patch-client-profile ]; then
   echo
   echo " +--------------------------------------------------------+"
   echo " |  No patch-client-profile file found in this directory  |"
   echo " +--------------------------------------------------------+"
   echo
   exit
else
   source patch-client-profile
fi

# +------------------------------------------+
# | OS REPOSITORY                            |
# +------------------------------------------+
FILE=/etc/yum.repos.d/hopper-repo.repo
if [ ! -f $FILE ]; then
   yum-config-manager --disable base
   yum-config-manager --disable extras
   yum-config-manager --disable updates
   echo "[hopper-repo]" > $FILE
   echo "name=Hopper-Stack $VERSION" >> $FILE
   echo "baseurl=http://$FILESERVER/$OSFLAVOR/7/0" >> $FILE
   echo "gpgcheck=0" >> $FILE
   echo "enabled=1" >> $FILE
   yum --enablerepo=hopper-repo clean metadata > /dev/null 2>&1
   yum update -y
   reboot
fi

